name: django CMS Content Expiry linters.yml

on: [pull_request]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install --upgrade flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: |
            flake8
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - run: python -m pip install isort
     - name: isort
       uses: liskin/gh-problem-matcher-wrap@v1
       with:
         linters: isort
         run: isort -c -rc -df ./

